services:

    mysql:
        env_file:
            -   ".env.local"
        image: mysql:8.0
        ports:
            - "3306:3306"
        environment:
            MYSQL_USER: ${DOCKER_USER}
            MYSQL_PASSWORD: ${DOCKER_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${DOCKER_ROOT_PASSWORD}
            MYSQL_DATABASE: ${DOCKER_DATABASE}
        volumes:
            -   mysql_rocket_cms:/var/lib/mysql

    phpmyadmin:
        env_file:
            -   ".env.local"
        image: phpmyadmin
        ports:
            - "8080:80"
        environment:
            PMA_HOST: mysql
            PMA_PORT: 3306
            PMA_USER: ${DOCKER_USER}
            PMA_PASSWORD: ${DOCKER_PASSWORD}
            PMA_ARBITRARY: 1

volumes:
    caddy_data:
    caddy_config:
    mysql_rocket_cms:

